### PR TITLE
Add recommendation model

### PR DESCRIPTION
**Pull request by cheryl1223**
Models
------
Recommendation - A Recommendation used in the Recommendation database

Attributes:
-----------
id (int) - the identity of the Recommendation
product_id (int) - the identity of the product that the recommendation is for
customer_id (int) - the identity of the customer that the recommendation is for
recommend_type (string) - the recommend_type of the recommendation (upscale, downscale, etc)
recommend_product_id (int) - the identity of recommended product

Methods
-----------
```
save()
delete()
serialize()
deserialize(data)
init_db(app)
all()
```

Tests
-----------
```
vagrant@flask:/vagrant$ nosetests

Test Cases for Recommendations 
- Create a recommendation and add it to the database
- Create a recommendation and assert that it exists
- Delete a Recommendation
- Test deserialization of a Recommendation
- Test deserialization of bad data
- Test deserialization of a Recommendation with missing data
- Test deserialization of no data
- Test serialization of a Recommendation
- Update a Recommendation

Name                  Stmts   Miss  Cover
-----------------------------------------
service/__init__.py      11      0   100%
service/models.py        46      0   100%
-----------------------------------------
TOTAL                    57      0   100%
----------------------------------------------------------------------
Ran 9 tests in 0.842s

OK

```

### CODE REVIEW

**Comment by YayunFan** [comment]
Good job!

**Review by YayunFan — APPROVED** [review]
Excellent work!

**Review by YayunFan — APPROVED** [review]
Excellent Work!

**Comment by qijinze911** [comment]
Good work！

**Pull request merged**
